### ISSUE TITLE
Comments on pigeon.md

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma-docs#1]
1. Pigeon setup should logically come after system configuration and setting up a validator. 
2. Why is this needed? https://github.com/palomachain/paloma-docs/blob/349871e374d1f7efb90d0fa123235bfcf70f4b39/docs/src/guide/pigeon.md?plain=1#L113
3. We're creating a new file here. We're not updating the env.sh file https://github.com/palomachain/paloma-docs/blob/349871e374d1f7efb90d0fa123235bfcf70f4b39/docs/src/guide/pigeon.md?plain=1#L116

**Comment by DannyS03** [comment]
Thanks @verabehr. I was thinking of creating a Relayer sub-section (so general info + configuration) and one for oracles, both under "Maintain". I believe you can run Pigeon without the needing to set up a validator.

> 2. Why is this needed? https://github.com/palomachain/paloma-docs/blob/349871e374d1f7efb90d0fa123235bfcf70f4b39/docs/src/guide/pigeon.md?plain=1#L113
> 3. We're creating a new file here. We're not updating the env.sh file https://github.com/palomachain/paloma-docs/blob/349871e374d1f7efb90d0fa123235bfcf70f4b39/docs/src/guide/pigeon.md?plain=1#L116

``` touch ~/.pigeon/env.sh``` is creating a new empty script, and then the script is populated.
